# Generated by Django 3.2.6 on 2021-08-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210815_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactions',
            old_name='tgt_obj_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='reactions',
            old_name='tgt_obj_id',
            new_name='object_id',
        ),
    ]
