# Generated by Django 3.2.6 on 2021-08-16 01:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='dislike',
            field=models.ManyToManyField(related_name='blogdislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='like',
            field=models.ManyToManyField(related_name='bloglike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blog',
            name='love',
            field=models.ManyToManyField(related_name='bloglove', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='dislike',
            field=models.ManyToManyField(related_name='commentdislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='like',
            field=models.ManyToManyField(related_name='commentlike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comments',
            name='love',
            field=models.ManyToManyField(related_name='commentlove', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='dislike',
            field=models.ManyToManyField(related_name='replydislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='like',
            field=models.ManyToManyField(related_name='replylike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='love',
            field=models.ManyToManyField(related_name='replylove', to=settings.AUTH_USER_MODEL),
        ),
    ]
